export const zones = [
  "Africa",
  "America",
  "Antarctica",
  "Arctic",
  "Asia",
  "Atlantic",
  "Australia",
  "Brazil",
  "Canada",
  "CET",
  "Chile",
  "CST6CDT",
  "Cuba",
  "EET",
  "Egypt",
  "Eire",
  "EST",
  "EST5EDT",
  "Etc",
  "Europe",
  "GB",
  "GB-Eire",
  "GMT",
  "GMT-0",
  "GMT+0",
  "GMT0",
  "Greenwich",
  "Hongkong",
  "HST",
  "Iceland",
  "Indian",
  "Iran",
  "Israel",
  "Jamaica",
  "Japan",
  "Kwajalein",
  "Libya",
  "MET",
  "Mexico",
  "MST",
  "MST7MDT",
  "Navajo",
  "NZ",
  "NZ-CHAT",
  "Pacific",
  "Poland",
  "Portugal",
  "PRC",
  "PST8PDT",
  "ROC",
  "ROK",
  "Singapore",
  "Turkey",
  "UCT",
  "Universal",
  "US",
  "UTC",
  "W-SU",
  "WET",
  "Zulu",
];

export const timezones = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Timbuktu",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/ComodRivadavia",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Atka",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Ciudad_Juarez",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Coyhaique",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Ensenada",
  "America/Fort_Nelson",
  "America/Fort_Wayne",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Knox_IN",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Nuuk",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port_of_Spain",
  "America/Port-au-Prince",
  "America/Porto_Acre",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Rosario",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Virgin",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/South_Pole",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Ashkhabad",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Chongqing",
  "Asia/Chungking",
  "Asia/Colombo",
  "Asia/Dacca",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Istanbul",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Kathmandu",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macao",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Tel_Aviv",
  "Asia/Thimbu",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ujung_Pandang",
  "Asia/Ulaanbaatar",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yangon",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Faroe",
  "Atlantic/Jan_Mayen",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/ACT",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Canberra",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/LHI",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/North",
  "Australia/NSW",
  "Australia/Perth",
  "Australia/Queensland",
  "Australia/South",
  "Australia/Sydney",
  "Australia/Tasmania",
  "Australia/Victoria",
  "Australia/West",
  "Australia/Yancowinna",
  "Brazil/Acre",
  "Brazil/DeNoronha",
  "Brazil/East",
  "Brazil/West",
  "Canada/Atlantic",
  "Canada/Central",
  "Canada/Eastern",
  "Canada/Mountain",
  "Canada/Newfoundland",
  "Canada/Pacific",
  "Canada/Saskatchewan",
  "Canada/Yukon",
  "CET",
  "Chile/Continental",
  "Chile/EasterIsland",
  "CST6CDT",
  "Cuba",
  "EET",
  "Egypt",
  "Eire",
  "EST",
  "EST5EDT",
  "Etc/GMT",
  "Etc/GMT-0",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Etc/GMT+0",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT0",
  "Etc/Greenwich",
  "Etc/UCT",
  "Etc/Universal",
  "Etc/UTC",
  "Etc/Zulu",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belfast",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Kyiv",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Nicosia",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Tiraspol",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "GB",
  "GB-Eire",
  "GMT",
  "GMT-0",
  "GMT+0",
  "GMT0",
  "Greenwich",
  "Hongkong",
  "HST",
  "Iceland",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Iran",
  "Israel",
  "Jamaica",
  "Japan",
  "Kwajalein",
  "Libya",
  "MET",
  "Mexico/BajaNorte",
  "Mexico/BajaSur",
  "Mexico/General",
  "MST",
  "MST7MDT",
  "Navajo",
  "NZ",
  "NZ-CHAT",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kanton",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Samoa",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
  "Pacific/Yap",
  "Poland",
  "Portugal",
  "PRC",
  "PST8PDT",
  "ROC",
  "ROK",
  "Singapore",
  "Turkey",
  "UCT",
  "Universal",
  "US/Alaska",
  "US/Aleutian",
  "US/Arizona",
  "US/Central",
  "US/East-Indiana",
  "US/Eastern",
  "US/Hawaii",
  "US/Indiana-Starke",
  "US/Michigan",
  "US/Mountain",
  "US/Pacific",
  "US/Samoa",
  "UTC",
  "W-SU",
  "WET",
  "Zulu",
];

export const timezoneMap = [
  {
    canonicalName: "Pacific/Midway",
    code: "SST",
    displayName: "Midway Island",
    displayWithOffset: "(-11:00) Midway Island",
    offset: -11.0,
  },
  {
    canonicalName: "Pacific/Pago_Pago",
    code: "SST",
    displayName: "American Samoa",
    displayWithOffset: "(-11:00) American Samoa",
    offset: -11.0,
  },
  {
    canonicalName: "Pacific/Midway",
    code: "SST",
    displayName: "International Date Line West",
    displayWithOffset: "(-11:00) International Date Line West",
    offset: -11.0,
  },
  {
    canonicalName: "Pacific/Honolulu",
    code: "HST",
    displayName: "Hawaii",
    displayWithOffset: "(-10:00) Hawaii",
    offset: -10.0,
  },
  {
    canonicalName: "America/Juneau",
    code: "AKDT",
    displayName: "Alaska",
    displayWithOffset: "(-08:00) Alaska",
    offset: -8.0,
  },
  {
    canonicalName: "America/Phoenix",
    code: "MST",
    displayName: "Arizona",
    displayWithOffset: "(-07:00) Arizona",
    offset: -7.0,
  },
  {
    canonicalName: "America/Los_Angeles",
    code: "PDT",
    displayName: "Pacific Time (US & Canada)",
    displayWithOffset: "(-07:00) Pacific Time (US & Canada)",
    offset: -7.0,
  },
  {
    canonicalName: "America/Mazatlan",
    code: "MST",
    displayName: "Mazatlan",
    displayWithOffset: "(-07:00) Mazatlan",
    offset: -7.0,
  },
  {
    canonicalName: "America/Tijuana",
    code: "PDT",
    displayName: "Tijuana",
    displayWithOffset: "(-07:00) Tijuana",
    offset: -7.0,
  },
  {
    canonicalName: "America/Monterrey",
    code: "CST",
    displayName: "Monterrey",
    displayWithOffset: "(-06:00) Monterrey",
    offset: -6.0,
  },
  {
    canonicalName: "America/Regina",
    code: "CST",
    displayName: "Saskatchewan",
    displayWithOffset: "(-06:00) Saskatchewan",
    offset: -6.0,
  },
  {
    canonicalName: "America/Mexico_City",
    code: "CST",
    displayName: "Mexico City",
    displayWithOffset: "(-06:00) Mexico City",
    offset: -6.0,
  },
  {
    canonicalName: "America/Guatemala",
    code: "CST",
    displayName: "Central America",
    displayWithOffset: "(-06:00) Central America",
    offset: -6.0,
  },
  {
    canonicalName: "America/Denver",
    code: "MDT",
    displayName: "Mountain Time (US & Canada)",
    displayWithOffset: "(-06:00) Mountain Time (US & Canada)",
    offset: -6.0,
  },
  {
    canonicalName: "America/Mexico_City",
    code: "CST",
    displayName: "Guadalajara",
    displayWithOffset: "(-06:00) Guadalajara",
    offset: -6.0,
  },
  {
    canonicalName: "America/Chihuahua",
    code: "CST",
    displayName: "Chihuahua",
    displayWithOffset: "(-06:00) Chihuahua",
    offset: -6.0,
  },
  {
    canonicalName: "America/Lima",
    code: "PET",
    displayName: "Quito",
    displayWithOffset: "(-05:00) Quito",
    offset: -5.0,
  },
  {
    canonicalName: "America/Bogota",
    code: "COT",
    displayName: "Bogota",
    displayWithOffset: "(-05:00) Bogota",
    offset: -5.0,
  },
  {
    canonicalName: "America/Lima",
    code: "PET",
    displayName: "Lima",
    displayWithOffset: "(-05:00) Lima",
    offset: -5.0,
  },
  {
    canonicalName: "America/Chicago",
    code: "CDT",
    displayName: "Central Time (US & Canada)",
    displayWithOffset: "(-05:00) Central Time (US & Canada)",
    offset: -5.0,
  },
  {
    canonicalName: "America/Indiana/Indianapolis",
    code: "EDT",
    displayName: "Indiana (East)",
    displayWithOffset: "(-04:00) Indiana (East)",
    offset: -4.0,
  },
  {
    canonicalName: "America/Guyana",
    code: "GYT",
    displayName: "Georgetown",
    displayWithOffset: "(-04:00) Georgetown",
    offset: -4.0,
  },
  {
    canonicalName: "America/Santiago",
    code: "CLT",
    displayName: "Santiago",
    displayWithOffset: "(-04:00) Santiago",
    offset: -4.0,
  },
  {
    canonicalName: "America/La_Paz",
    code: "BOT",
    displayName: "La Paz",
    displayWithOffset: "(-04:00) La Paz",
    offset: -4.0,
  },
  {
    canonicalName: "America/New_York",
    code: "EDT",
    displayName: "Eastern Time (US & Canada)",
    displayWithOffset: "(-04:00) Eastern Time (US & Canada)",
    offset: -4.0,
  },
  {
    canonicalName: "America/Caracas",
    code: "VET",
    displayName: "Caracas",
    displayWithOffset: "(-04:00) Caracas",
    offset: -4.0,
  },
  {
    canonicalName: "America/Argentina/Buenos_Aires",
    code: "ART",
    displayName: "Buenos Aires",
    displayWithOffset: "(-03:00) Buenos Aires",
    offset: -3.0,
  },
  {
    canonicalName: "America/Sao_Paulo",
    code: "BRT",
    displayName: "Brasilia",
    displayWithOffset: "(-03:00) Brasilia",
    offset: -3.0,
  },
  {
    canonicalName: "America/Montevideo",
    code: "UYT",
    displayName: "Montevideo",
    displayWithOffset: "(-03:00) Montevideo",
    offset: -3.0,
  },
  {
    canonicalName: "America/Halifax",
    code: "ADT",
    displayName: "Atlantic Time (Canada)",
    displayWithOffset: "(-03:00) Atlantic Time (Canada)",
    offset: -3.0,
  },
  {
    canonicalName: "America/St_Johns",
    code: "NDT",
    displayName: "Newfoundland",
    displayWithOffset: "(-02:30) Newfoundland",
    offset: -2.5,
  },
  {
    canonicalName: "Atlantic/South_Georgia",
    code: "GST",
    displayName: "Mid-Atlantic",
    displayWithOffset: "(-02:00) Mid-Atlantic",
    offset: -2.0,
  },
  {
    canonicalName: "Atlantic/Cape_Verde",
    code: "CVT",
    displayName: "Cape Verde Is.",
    displayWithOffset: "(-01:00) Cape Verde Is.",
    offset: -1.0,
  },
  {
    canonicalName: "America/Godthab",
    code: "WGST",
    displayName: "Greenland",
    displayWithOffset: "(-01:00) Greenland",
    offset: -1.0,
  },
  {
    canonicalName: "Atlantic/Azores",
    code: "AZOST",
    displayName: "Azores",
    displayWithOffset: "(-00:00) Azores",
    offset: 0.0,
  },
  {
    canonicalName: "Etc/UTC",
    code: "UTC",
    displayName: "UTC",
    displayWithOffset: "(-00:00) UTC",
    offset: 0.0,
  },
  {
    canonicalName: "Africa/Monrovia",
    code: "GMT",
    displayName: "Monrovia",
    displayWithOffset: "(-00:00) Monrovia",
    offset: 0.0,
  },
  {
    canonicalName: "Africa/Casablanca",
    code: "WEST",
    displayName: "Casablanca",
    displayWithOffset: "(+01:00) Casablanca",
    offset: 1.0,
  },
  {
    canonicalName: "Africa/Algiers",
    code: "CET",
    displayName: "West Central Africa",
    displayWithOffset: "(+01:00) West Central Africa",
    offset: 1.0,
  },
  {
    canonicalName: "Europe/Lisbon",
    code: "WEST",
    displayName: "Lisbon",
    displayWithOffset: "(+01:00) Lisbon",
    offset: 1.0,
  },
  {
    canonicalName: "Europe/London",
    code: "BST",
    displayName: "London",
    displayWithOffset: "(+01:00) London",
    offset: 1.0,
  },
  {
    canonicalName: "Europe/Dublin",
    code: "IST",
    displayName: "Dublin",
    displayWithOffset: "(+01:00) Dublin",
    offset: 1.0,
  },
  {
    canonicalName: "Europe/London",
    code: "BST",
    displayName: "Edinburgh",
    displayWithOffset: "(+01:00) Edinburgh",
    offset: 1.0,
  },
  {
    canonicalName: "Europe/Belgrade",
    code: "CEST",
    displayName: "Belgrade",
    displayWithOffset: "(+02:00) Belgrade",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Copenhagen",
    code: "CEST",
    displayName: "Copenhagen",
    displayWithOffset: "(+02:00) Copenhagen",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Warsaw",
    code: "CEST",
    displayName: "Warsaw",
    displayWithOffset: "(+02:00) Warsaw",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Budapest",
    code: "CEST",
    displayName: "Budapest",
    displayWithOffset: "(+02:00) Budapest",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Madrid",
    code: "CEST",
    displayName: "Madrid",
    displayWithOffset: "(+02:00) Madrid",
    offset: 2.0,
  },
  {
    canonicalName: "Africa/Harare",
    code: "CAT",
    displayName: "Harare",
    displayWithOffset: "(+02:00) Harare",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Amsterdam",
    code: "CEST",
    displayName: "Amsterdam",
    displayWithOffset: "(+02:00) Amsterdam",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Rome",
    code: "CEST",
    displayName: "Rome",
    displayWithOffset: "(+02:00) Rome",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Zagreb",
    code: "CEST",
    displayName: "Zagreb",
    displayWithOffset: "(+02:00) Zagreb",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Sarajevo",
    code: "CEST",
    displayName: "Sarajevo",
    displayWithOffset: "(+02:00) Sarajevo",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Brussels",
    code: "CEST",
    displayName: "Brussels",
    displayWithOffset: "(+02:00) Brussels",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Berlin",
    code: "CEST",
    displayName: "Berlin",
    displayWithOffset: "(+02:00) Berlin",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Bratislava",
    code: "CEST",
    displayName: "Bratislava",
    displayWithOffset: "(+02:00) Bratislava",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Stockholm",
    code: "CEST",
    displayName: "Stockholm",
    displayWithOffset: "(+02:00) Stockholm",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Prague",
    code: "CEST",
    displayName: "Prague",
    displayWithOffset: "(+02:00) Prague",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Berlin",
    code: "CEST",
    displayName: "Bern",
    displayWithOffset: "(+02:00) Bern",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Vienna",
    code: "CEST",
    displayName: "Vienna",
    displayWithOffset: "(+02:00) Vienna",
    offset: 2.0,
  },
  {
    canonicalName: "Africa/Johannesburg",
    code: "SAST",
    displayName: "Pretoria",
    displayWithOffset: "(+02:00) Pretoria",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Ljubljana",
    code: "CEST",
    displayName: "Ljubljana",
    displayWithOffset: "(+02:00) Ljubljana",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Skopje",
    code: "CEST",
    displayName: "Skopje",
    displayWithOffset: "(+02:00) Skopje",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Paris",
    code: "CEST",
    displayName: "Paris",
    displayWithOffset: "(+02:00) Paris",
    offset: 2.0,
  },
  {
    canonicalName: "Europe/Bucharest",
    code: "EEST",
    displayName: "Bucharest",
    displayWithOffset: "(+03:00) Bucharest",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Kiev",
    code: "EEST",
    displayName: "Kyiv",
    displayWithOffset: "(+03:00) Kyiv",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Istanbul",
    code: "TRT",
    displayName: "Istanbul",
    displayWithOffset: "(+03:00) Istanbul",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Moscow",
    code: "MSK",
    displayName: "St. Petersburg",
    displayWithOffset: "(+03:00) St. Petersburg",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Athens",
    code: "EEST",
    displayName: "Athens",
    displayWithOffset: "(+03:00) Athens",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Moscow",
    code: "MSK",
    displayName: "Moscow",
    displayWithOffset: "(+03:00) Moscow",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Riga",
    code: "EEST",
    displayName: "Riga",
    displayWithOffset: "(+03:00) Riga",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Helsinki",
    code: "EEST",
    displayName: "Helsinki",
    displayWithOffset: "(+03:00) Helsinki",
    offset: 3.0,
  },
  {
    canonicalName: "Asia/Kuwait",
    code: "AST",
    displayName: "Kuwait",
    displayWithOffset: "(+03:00) Kuwait",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Minsk",
    code: "MSK",
    displayName: "Minsk",
    displayWithOffset: "(+03:00) Minsk",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Moscow",
    code: "MSK",
    displayName: "Volgograd",
    displayWithOffset: "(+03:00) Volgograd",
    offset: 3.0,
  },
  {
    canonicalName: "Asia/Riyadh",
    code: "AST",
    displayName: "Riyadh",
    displayWithOffset: "(+03:00) Riyadh",
    offset: 3.0,
  },
  {
    canonicalName: "Africa/Nairobi",
    code: "EAT",
    displayName: "Nairobi",
    displayWithOffset: "(+03:00) Nairobi",
    offset: 3.0,
  },
  {
    canonicalName: "Asia/Jerusalem",
    code: "IDT",
    displayName: "Jerusalem",
    displayWithOffset: "(+03:00) Jerusalem",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Vilnius",
    code: "EEST",
    displayName: "Vilnius",
    displayWithOffset: "(+03:00) Vilnius",
    offset: 3.0,
  },
  {
    canonicalName: "Asia/Baghdad",
    code: "AST",
    displayName: "Baghdad",
    displayWithOffset: "(+03:00) Baghdad",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Sofia",
    code: "EEST",
    displayName: "Sofia",
    displayWithOffset: "(+03:00) Sofia",
    offset: 3.0,
  },
  {
    canonicalName: "Europe/Tallinn",
    code: "EEST",
    displayName: "Tallinn",
    displayWithOffset: "(+03:00) Tallinn",
    offset: 3.0,
  },
  {
    canonicalName: "Africa/Cairo",
    code: "EEST",
    displayName: "Cairo",
    displayWithOffset: "(+03:00) Cairo",
    offset: 3.0,
  },
  {
    canonicalName: "Asia/Tehran",
    code: "IRST",
    displayName: "Tehran",
    displayWithOffset: "(+03:30) Tehran",
    offset: 3.5,
  },
  {
    canonicalName: "Asia/Baku",
    code: "AZT",
    displayName: "Baku",
    displayWithOffset: "(+04:00) Baku",
    offset: 4.0,
  },
  {
    canonicalName: "Asia/Muscat",
    code: "GST",
    displayName: "Abu Dhabi",
    displayWithOffset: "(+04:00) Abu Dhabi",
    offset: 4.0,
  },
  {
    canonicalName: "Asia/Muscat",
    code: "GST",
    displayName: "Muscat",
    displayWithOffset: "(+04:00) Muscat",
    offset: 4.0,
  },
  {
    canonicalName: "Asia/Tbilisi",
    code: "GET",
    displayName: "Tbilisi",
    displayWithOffset: "(+04:00) Tbilisi",
    offset: 4.0,
  },
  {
    canonicalName: "Asia/Yerevan",
    code: "AMT",
    displayName: "Yerevan",
    displayWithOffset: "(+04:00) Yerevan",
    offset: 4.0,
  },
  {
    canonicalName: "Asia/Kabul",
    code: "AFT",
    displayName: "Kabul",
    displayWithOffset: "(+04:30) Kabul",
    offset: 4.5,
  },
  {
    canonicalName: "Asia/Tashkent",
    code: "UZT",
    displayName: "Tashkent",
    displayWithOffset: "(+05:00) Tashkent",
    offset: 5.0,
  },
  {
    canonicalName: "Asia/Karachi",
    code: "PKT",
    displayName: "Karachi",
    displayWithOffset: "(+05:00) Karachi",
    offset: 5.0,
  },
  {
    canonicalName: "Asia/Karachi",
    code: "PKT",
    displayName: "Islamabad",
    displayWithOffset: "(+05:00) Islamabad",
    offset: 5.0,
  },
  {
    canonicalName: "Asia/Yekaterinburg",
    code: "YEKT",
    displayName: "Ekaterinburg",
    displayWithOffset: "(+05:00) Ekaterinburg",
    offset: 5.0,
  },
  {
    canonicalName: "Asia/Almaty",
    code: "ALMT",
    displayName: "Almaty",
    displayWithOffset: "(+05:00) Almaty",
    offset: 5.0,
  },
  {
    canonicalName: "Asia/Kolkata",
    code: "IST",
    displayName: "Chennai",
    displayWithOffset: "(+05:30) Chennai",
    offset: 5.5,
  },
  {
    canonicalName: "Asia/Kolkata",
    code: "IST",
    displayName: "Mumbai",
    displayWithOffset: "(+05:30) Mumbai",
    offset: 5.5,
  },
  {
    canonicalName: "Asia/Kolkata",
    code: "IST",
    displayName: "Kolkata",
    displayWithOffset: "(+05:30) Kolkata",
    offset: 5.5,
  },
  {
    canonicalName: "Asia/Kolkata",
    code: "IST",
    displayName: "New Delhi",
    displayWithOffset: "(+05:30) New Delhi",
    offset: 5.5,
  },
  {
    canonicalName: "Asia/Colombo",
    code: "IST",
    displayName: "Sri Jayawardenepura",
    displayWithOffset: "(+05:30) Sri Jayawardenepura",
    offset: 5.5,
  },
  {
    canonicalName: "Asia/Kathmandu",
    code: "NPT",
    displayName: "Kathmandu",
    displayWithOffset: "(+05:45) Kathmandu",
    offset: 5.75,
  },
  {
    canonicalName: "Asia/Dhaka",
    code: "BDT",
    displayName: "Astana",
    displayWithOffset: "(+06:00) Astana",
    offset: 6.0,
  },
  {
    canonicalName: "Asia/Urumqi",
    code: "XJT",
    displayName: "Urumqi",
    displayWithOffset: "(+06:00) Urumqi",
    offset: 6.0,
  },
  {
    canonicalName: "Asia/Dhaka",
    code: "BDT",
    displayName: "Dhaka",
    displayWithOffset: "(+06:00) Dhaka",
    offset: 6.0,
  },
  {
    canonicalName: "Asia/Rangoon",
    code: "MMT",
    displayName: "Rangoon",
    displayWithOffset: "(+06:30) Rangoon",
    offset: 6.5,
  },
  {
    canonicalName: "Asia/Bangkok",
    code: "ICT",
    displayName: "Hanoi",
    displayWithOffset: "(+07:00) Hanoi",
    offset: 7.0,
  },
  {
    canonicalName: "Asia/Bangkok",
    code: "ICT",
    displayName: "Bangkok",
    displayWithOffset: "(+07:00) Bangkok",
    offset: 7.0,
  },
  {
    canonicalName: "Asia/Jakarta",
    code: "WIB",
    displayName: "Jakarta",
    displayWithOffset: "(+07:00) Jakarta",
    offset: 7.0,
  },
  {
    canonicalName: "Asia/Novosibirsk",
    code: "NOVT",
    displayName: "Novosibirsk",
    displayWithOffset: "(+07:00) Novosibirsk",
    offset: 7.0,
  },
  {
    canonicalName: "Asia/Krasnoyarsk",
    code: "KRAT",
    displayName: "Krasnoyarsk",
    displayWithOffset: "(+07:00) Krasnoyarsk",
    offset: 7.0,
  },
  {
    canonicalName: "Asia/Shanghai",
    code: "CST",
    displayName: "Beijing",
    displayWithOffset: "(+08:00) Beijing",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Irkutsk",
    code: "IRKT",
    displayName: "Irkutsk",
    displayWithOffset: "(+08:00) Irkutsk",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Hong_Kong",
    code: "HKT",
    displayName: "Hong Kong",
    displayWithOffset: "(+08:00) Hong Kong",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Ulaanbaatar",
    code: "ULAT",
    displayName: "Ulaanbaatar",
    displayWithOffset: "(+08:00) Ulaanbaatar",
    offset: 8.0,
  },
  {
    canonicalName: "Australia/Perth",
    code: "AWST",
    displayName: "Perth",
    displayWithOffset: "(+08:00) Perth",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Singapore",
    code: "SGT",
    displayName: "Singapore",
    displayWithOffset: "(+08:00) Singapore",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Taipei",
    code: "CST",
    displayName: "Taipei",
    displayWithOffset: "(+08:00) Taipei",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Kuala_Lumpur",
    code: "MYT",
    displayName: "Kuala Lumpur",
    displayWithOffset: "(+08:00) Kuala Lumpur",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Chongqing",
    code: "CST",
    displayName: "Chongqing",
    displayWithOffset: "(+08:00) Chongqing",
    offset: 8.0,
  },
  {
    canonicalName: "Asia/Yakutsk",
    code: "YAKT",
    displayName: "Yakutsk",
    displayWithOffset: "(+09:00) Yakutsk",
    offset: 9.0,
  },
  {
    canonicalName: "Asia/Seoul",
    code: "KST",
    displayName: "Seoul",
    displayWithOffset: "(+09:00) Seoul",
    offset: 9.0,
  },
  {
    canonicalName: "Asia/Tokyo",
    code: "JST",
    displayName: "Osaka",
    displayWithOffset: "(+09:00) Osaka",
    offset: 9.0,
  },
  {
    canonicalName: "Asia/Tokyo",
    code: "JST",
    displayName: "Tokyo",
    displayWithOffset: "(+09:00) Tokyo",
    offset: 9.0,
  },
  {
    canonicalName: "Asia/Tokyo",
    code: "JST",
    displayName: "Sapporo",
    displayWithOffset: "(+09:00) Sapporo",
    offset: 9.0,
  },
  {
    canonicalName: "Australia/Adelaide",
    code: "ACST",
    displayName: "Adelaide",
    displayWithOffset: "(+09:30) Adelaide",
    offset: 9.5,
  },
  {
    canonicalName: "Australia/Darwin",
    code: "ACST",
    displayName: "Darwin",
    displayWithOffset: "(+09:30) Darwin",
    offset: 9.5,
  },
  {
    canonicalName: "Australia/Melbourne",
    code: "AEST",
    displayName: "Canberra",
    displayWithOffset: "(+10:00) Canberra",
    offset: 10.0,
  },
  {
    canonicalName: "Australia/Sydney",
    code: "AEST",
    displayName: "Sydney",
    displayWithOffset: "(+10:00) Sydney",
    offset: 10.0,
  },
  {
    canonicalName: "Australia/Hobart",
    code: "AEST",
    displayName: "Hobart",
    displayWithOffset: "(+10:00) Hobart",
    offset: 10.0,
  },
  {
    canonicalName: "Pacific/Port_Moresby",
    code: "PGT",
    displayName: "Port Moresby",
    displayWithOffset: "(+10:00) Port Moresby",
    offset: 10.0,
  },
  {
    canonicalName: "Asia/Vladivostok",
    code: "VLAT",
    displayName: "Vladivostok",
    displayWithOffset: "(+10:00) Vladivostok",
    offset: 10.0,
  },
  {
    canonicalName: "Australia/Melbourne",
    code: "AEST",
    displayName: "Melbourne",
    displayWithOffset: "(+10:00) Melbourne",
    offset: 10.0,
  },
  {
    canonicalName: "Australia/Brisbane",
    code: "AEST",
    displayName: "Brisbane",
    displayWithOffset: "(+10:00) Brisbane",
    offset: 10.0,
  },
  {
    canonicalName: "Pacific/Guam",
    code: "ChST",
    displayName: "Guam",
    displayWithOffset: "(+10:00) Guam",
    offset: 10.0,
  },
  {
    canonicalName: "Pacific/Noumea",
    code: "NCT",
    displayName: "New Caledonia",
    displayWithOffset: "(+11:00) New Caledonia",
    offset: 11.0,
  },
  {
    canonicalName: "Pacific/Guadalcanal",
    code: "SBT",
    displayName: "Solomon Is.",
    displayWithOffset: "(+11:00) Solomon Is.",
    offset: 11.0,
  },
  {
    canonicalName: "Asia/Magadan",
    code: "MAGT",
    displayName: "Magadan",
    displayWithOffset: "(+11:00) Magadan",
    offset: 11.0,
  },
  {
    canonicalName: "Asia/Kamchatka",
    code: "PETT",
    displayName: "Kamchatka",
    displayWithOffset: "(+12:00) Kamchatka",
    offset: 12.0,
  },
  {
    canonicalName: "Pacific/Auckland",
    code: "NZST",
    displayName: "Wellington",
    displayWithOffset: "(+12:00) Wellington",
    offset: 12.0,
  },
  {
    canonicalName: "Pacific/Majuro",
    code: "MHT",
    displayName: "Marshall Is.",
    displayWithOffset: "(+12:00) Marshall Is.",
    offset: 12.0,
  },
  {
    canonicalName: "Pacific/Fiji",
    code: "FJT",
    displayName: "Fiji",
    displayWithOffset: "(+12:00) Fiji",
    offset: 12.0,
  },
  {
    canonicalName: "Pacific/Auckland",
    code: "NZST",
    displayName: "Auckland",
    displayWithOffset: "(+12:00) Auckland",
    offset: 12.0,
  },
  {
    canonicalName: "Pacific/Chatham",
    code: "CHAST",
    displayName: "Chatham Is.",
    displayWithOffset: "(+12:45) Chatham Is.",
    offset: 12.75,
  },
  {
    canonicalName: "Pacific/Apia",
    code: "WSST",
    displayName: "Samoa",
    displayWithOffset: "(+13:00) Samoa",
    offset: 13.0,
  },
  {
    canonicalName: "Pacific/Tongatapu",
    code: "TOT",
    displayName: "Nuku'alofa",
    displayWithOffset: "(+13:00) Nuku'alofa",
    offset: 13.0,
  },
  {
    canonicalName: "Pacific/Fakaofo",
    code: "TKT",
    displayName: "Tokelau Is.",
    displayWithOffset: "(+13:00) Tokelau Is.",
    offset: 13.0,
  },
];
